// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzUpFa2MCcC5CR4-DVTzvtWTeW0bvJwg',
    appId: '1:797970486297:web:fc2d6364f3a0c065298688',
    messagingSenderId: '797970486297',
    projectId: 'personal-nutrition-control',
    authDomain: 'personal-nutrition-control.firebaseapp.com',
    storageBucket: 'personal-nutrition-control.appspot.com',
    measurementId: 'G-CRY2HGGG9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZfzVITMuLp5n7Z98ea7t50taGmYyhEE',
    appId: '1:797970486297:android:594f4fe9c0e21472298688',
    messagingSenderId: '797970486297',
    projectId: 'personal-nutrition-control',
    storageBucket: 'personal-nutrition-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuJlx5mVww3QKpbtW5omV1o_Eqd6KuHa0',
    appId: '1:797970486297:ios:d7b39279856dee36298688',
    messagingSenderId: '797970486297',
    projectId: 'personal-nutrition-control',
    storageBucket: 'personal-nutrition-control.appspot.com',
    iosBundleId: 'com.example.personalNutritionControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuJlx5mVww3QKpbtW5omV1o_Eqd6KuHa0',
    appId: '1:797970486297:ios:affb91f4e49d1d8c298688',
    messagingSenderId: '797970486297',
    projectId: 'personal-nutrition-control',
    storageBucket: 'personal-nutrition-control.appspot.com',
    iosBundleId: 'com.example.personalNutritionControl.RunnerTests',
  );
}
